"""init commit

Revision ID: 33e530663cb8
Revises: d6ea28af0171
Create Date: 2022-01-14 14:59:04.411920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e530663cb8'
down_revision = 'd6ea28af0171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ty_idc', sa.Column('vendor_fullname', sa.String(length=64), nullable=True, comment='供应商公司全称'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ty_idc', 'vendor_fullname')
    # ### end Alembic commands ###
