"""init commit

Revision ID: 39cc85072ef9
Revises: 
Create Date: 2022-01-13 17:46:43.597879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cc85072ef9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ty_vendor', sa.Column('comp_hash', sa.String(length=64), nullable=True, comment='HASH码'))
    op.create_index(op.f('ix_ty_vendor_comp_hash'), 'ty_vendor', ['comp_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ty_vendor_comp_hash'), table_name='ty_vendor')
    op.drop_column('ty_vendor', 'comp_hash')
    # ### end Alembic commands ###
