"""init commit

Revision ID: 5a0bfdcb8a24
Revises: 996cd48cd53b
Create Date: 2022-01-14 16:26:28.532674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0bfdcb8a24'
down_revision = '996cd48cd53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ty_vlanid', sa.Column('country', sa.String(length=32), nullable=True, comment='所属国家'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ty_vlanid', 'country')
    # ### end Alembic commands ###
