"""init commit

Revision ID: 996cd48cd53b
Revises: 33e530663cb8
Create Date: 2022-01-14 14:59:40.262187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '996cd48cd53b'
down_revision = '33e530663cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ty_idc', sa.Column('vendor_name', sa.String(length=64), nullable=True, comment='供应商公司全称'))
    op.drop_column('ty_idc', 'vendor_fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ty_idc', sa.Column('vendor_fullname', mysql.VARCHAR(length=64), nullable=True, comment='供应商公司全称'))
    op.drop_column('ty_idc', 'vendor_name')
    # ### end Alembic commands ###
