"""init commit

Revision ID: b601b4e44700
Revises: 5a0bfdcb8a24
Create Date: 2022-01-17 09:34:41.654867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b601b4e44700'
down_revision = '5a0bfdcb8a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ty_city', sa.Column('created_by', sa.BIGINT(), nullable=True, comment='创建者ID，Ogcloud用户ID'))
    op.add_column('ty_city', sa.Column('created_at', sa.BIGINT(), nullable=True, comment='创建时间'))
    op.add_column('ty_city', sa.Column('updated_by', sa.BIGINT(), nullable=True, comment='更新者ID，Ogcloud用户ID'))
    op.add_column('ty_city', sa.Column('updated_at', sa.BIGINT(), nullable=True, comment='更新时间'))
    op.drop_column('ty_city', 'created_time')
    op.drop_column('ty_city', 'updated_time')
    op.add_column('ty_continent', sa.Column('created_by', sa.BIGINT(), nullable=True, comment='创建者ID，Ogcloud用户ID'))
    op.add_column('ty_continent', sa.Column('created_at', sa.BIGINT(), nullable=True, comment='创建时间'))
    op.add_column('ty_continent', sa.Column('updated_by', sa.BIGINT(), nullable=True, comment='更新者ID，Ogcloud用户ID'))
    op.add_column('ty_continent', sa.Column('updated_at', sa.BIGINT(), nullable=True, comment='更新时间'))
    op.drop_column('ty_continent', 'created_time')
    op.drop_column('ty_continent', 'updated_time')
    op.add_column('ty_country', sa.Column('created_by', sa.BIGINT(), nullable=True, comment='创建者ID，Ogcloud用户ID'))
    op.add_column('ty_country', sa.Column('created_at', sa.BIGINT(), nullable=True, comment='创建时间'))
    op.add_column('ty_country', sa.Column('updated_by', sa.BIGINT(), nullable=True, comment='更新者ID，Ogcloud用户ID'))
    op.add_column('ty_country', sa.Column('updated_at', sa.BIGINT(), nullable=True, comment='更新时间'))
    op.drop_column('ty_country', 'created_time')
    op.drop_column('ty_country', 'updated_time')
    op.add_column('ty_idc', sa.Column('created_by', sa.BIGINT(), nullable=True, comment='创建者ID，Ogcloud用户ID'))
    op.add_column('ty_idc', sa.Column('created_at', sa.BIGINT(), nullable=True, comment='创建时间'))
    op.add_column('ty_idc', sa.Column('updated_by', sa.BIGINT(), nullable=True, comment='更新者ID，Ogcloud用户ID'))
    op.add_column('ty_idc', sa.Column('updated_at', sa.BIGINT(), nullable=True, comment='更新时间'))
    op.drop_column('ty_idc', 'created_time')
    op.drop_column('ty_idc', 'updated_time')
    op.add_column('ty_ipaddr', sa.Column('created_by', sa.BIGINT(), nullable=True, comment='创建者ID，Ogcloud用户ID'))
    op.add_column('ty_ipaddr', sa.Column('created_at', sa.BIGINT(), nullable=True, comment='创建时间'))
    op.add_column('ty_ipaddr', sa.Column('updated_by', sa.BIGINT(), nullable=True, comment='更新者ID，Ogcloud用户ID'))
    op.add_column('ty_ipaddr', sa.Column('updated_at', sa.BIGINT(), nullable=True, comment='更新时间'))
    op.add_column('ty_ipaddr', sa.Column('ipaddr', sa.String(length=32), nullable=True, comment='IP，支持网段、IP地址、IP范围'))
    op.add_column('ty_ipaddr', sa.Column('ipver', sa.SMALLINT(), nullable=True, comment='Version，目前只支持IPv4'))
    op.add_column('ty_ipaddr', sa.Column('is_assigned', sa.SMALLINT(), nullable=True, comment='是否已被使用，0-否，1-是'))
    op.add_column('ty_ipaddr', sa.Column('idc_id', sa.BIGINT(), nullable=True, comment='机房ID'))
    op.add_column('ty_ipaddr', sa.Column('idc_name', sa.String(length=64), nullable=True, comment='机房名称'))
    op.alter_column('ty_ipaddr', 'assignment',
               existing_type=mysql.VARCHAR(length=128),
               comment='IP分配信息',
               existing_comment='IP分配与作用',
               existing_nullable=True)
    op.drop_index('ip', table_name='ty_ipaddr')
    op.drop_column('ty_ipaddr', 'created_time')
    op.drop_column('ty_ipaddr', 'updated_time')
    op.drop_column('ty_ipaddr', 'is_used')
    op.drop_column('ty_ipaddr', 'ip')
    op.add_column('ty_ipaddr_expand', sa.Column('created_by', sa.BIGINT(), nullable=True, comment='创建者ID，Ogcloud用户ID'))
    op.add_column('ty_ipaddr_expand', sa.Column('created_at', sa.BIGINT(), nullable=True, comment='创建时间'))
    op.add_column('ty_ipaddr_expand', sa.Column('updated_by', sa.BIGINT(), nullable=True, comment='更新者ID，Ogcloud用户ID'))
    op.add_column('ty_ipaddr_expand', sa.Column('updated_at', sa.BIGINT(), nullable=True, comment='更新时间'))
    op.add_column('ty_ipaddr_expand', sa.Column('ipaddr_id', sa.BIGINT(), nullable=True, comment='IP_ID'))
    op.drop_constraint('ty_ipaddr_expand_ibfk_1', 'ty_ipaddr_expand', type_='foreignkey')
    op.create_foreign_key(None, 'ty_ipaddr_expand', 'ty_ipaddr', ['ipaddr_id'], ['id'])
    op.drop_column('ty_ipaddr_expand', 'created_time')
    op.drop_column('ty_ipaddr_expand', 'updated_time')
    op.drop_column('ty_ipaddr_expand', 'iphash')
    op.add_column('ty_users', sa.Column('created_by', sa.BIGINT(), nullable=True, comment='创建者ID，Ogcloud用户ID'))
    op.add_column('ty_users', sa.Column('created_at', sa.BIGINT(), nullable=True, comment='创建时间'))
    op.add_column('ty_users', sa.Column('updated_by', sa.BIGINT(), nullable=True, comment='更新者ID，Ogcloud用户ID'))
    op.add_column('ty_users', sa.Column('updated_at', sa.BIGINT(), nullable=True, comment='更新时间'))
    op.drop_column('ty_users', 'created_time')
    op.drop_column('ty_users', 'updated_time')
    op.add_column('ty_vendor', sa.Column('created_by', sa.BIGINT(), nullable=True, comment='创建者ID，Ogcloud用户ID'))
    op.add_column('ty_vendor', sa.Column('created_at', sa.BIGINT(), nullable=True, comment='创建时间'))
    op.add_column('ty_vendor', sa.Column('updated_by', sa.BIGINT(), nullable=True, comment='更新者ID，Ogcloud用户ID'))
    op.add_column('ty_vendor', sa.Column('updated_at', sa.BIGINT(), nullable=True, comment='更新时间'))
    op.drop_column('ty_vendor', 'created_time')
    op.drop_column('ty_vendor', 'updated_time')
    op.add_column('ty_vlanid', sa.Column('created_by', sa.BIGINT(), nullable=True, comment='创建者ID，Ogcloud用户ID'))
    op.add_column('ty_vlanid', sa.Column('created_at', sa.BIGINT(), nullable=True, comment='创建时间'))
    op.add_column('ty_vlanid', sa.Column('updated_by', sa.BIGINT(), nullable=True, comment='更新者ID，Ogcloud用户ID'))
    op.add_column('ty_vlanid', sa.Column('updated_at', sa.BIGINT(), nullable=True, comment='更新时间'))
    op.add_column('ty_vlanid', sa.Column('idc_id', sa.BIGINT(), nullable=True, comment='机房ID'))
    op.add_column('ty_vlanid', sa.Column('idc_name', sa.String(length=64), nullable=True, comment='机房名称'))
    op.drop_column('ty_vlanid', 'created_time')
    op.drop_column('ty_vlanid', 'updated_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ty_vlanid', sa.Column('updated_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='更新时间'))
    op.add_column('ty_vlanid', sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建时间'))
    op.drop_column('ty_vlanid', 'idc_name')
    op.drop_column('ty_vlanid', 'idc_id')
    op.drop_column('ty_vlanid', 'updated_at')
    op.drop_column('ty_vlanid', 'updated_by')
    op.drop_column('ty_vlanid', 'created_at')
    op.drop_column('ty_vlanid', 'created_by')
    op.add_column('ty_vendor', sa.Column('updated_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='更新时间'))
    op.add_column('ty_vendor', sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建时间'))
    op.drop_column('ty_vendor', 'updated_at')
    op.drop_column('ty_vendor', 'updated_by')
    op.drop_column('ty_vendor', 'created_at')
    op.drop_column('ty_vendor', 'created_by')
    op.add_column('ty_users', sa.Column('updated_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='更新时间'))
    op.add_column('ty_users', sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建时间'))
    op.drop_column('ty_users', 'updated_at')
    op.drop_column('ty_users', 'updated_by')
    op.drop_column('ty_users', 'created_at')
    op.drop_column('ty_users', 'created_by')
    op.add_column('ty_ipaddr_expand', sa.Column('iphash', mysql.VARCHAR(length=64), nullable=True, comment='IP哈希码'))
    op.add_column('ty_ipaddr_expand', sa.Column('updated_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='更新时间'))
    op.add_column('ty_ipaddr_expand', sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建时间'))
    op.drop_constraint(None, 'ty_ipaddr_expand', type_='foreignkey')
    op.create_foreign_key('ty_ipaddr_expand_ibfk_1', 'ty_ipaddr_expand', 'ty_ipaddr', ['iphash'], ['iphash'])
    op.drop_column('ty_ipaddr_expand', 'ipaddr_id')
    op.drop_column('ty_ipaddr_expand', 'updated_at')
    op.drop_column('ty_ipaddr_expand', 'updated_by')
    op.drop_column('ty_ipaddr_expand', 'created_at')
    op.drop_column('ty_ipaddr_expand', 'created_by')
    op.add_column('ty_ipaddr', sa.Column('ip', mysql.VARCHAR(length=32), nullable=True, comment='IP，支持网段、IP地址、IP范围'))
    op.add_column('ty_ipaddr', sa.Column('is_used', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='是否已被使用，0-否，1-是'))
    op.add_column('ty_ipaddr', sa.Column('updated_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='更新时间'))
    op.add_column('ty_ipaddr', sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建时间'))
    op.create_index('ip', 'ty_ipaddr', ['ip'], unique=False)
    op.alter_column('ty_ipaddr', 'assignment',
               existing_type=mysql.VARCHAR(length=128),
               comment='IP分配与作用',
               existing_comment='IP分配信息',
               existing_nullable=True)
    op.drop_column('ty_ipaddr', 'idc_name')
    op.drop_column('ty_ipaddr', 'idc_id')
    op.drop_column('ty_ipaddr', 'is_assigned')
    op.drop_column('ty_ipaddr', 'ipver')
    op.drop_column('ty_ipaddr', 'ipaddr')
    op.drop_column('ty_ipaddr', 'updated_at')
    op.drop_column('ty_ipaddr', 'updated_by')
    op.drop_column('ty_ipaddr', 'created_at')
    op.drop_column('ty_ipaddr', 'created_by')
    op.add_column('ty_idc', sa.Column('updated_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='更新时间'))
    op.add_column('ty_idc', sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建时间'))
    op.drop_column('ty_idc', 'updated_at')
    op.drop_column('ty_idc', 'updated_by')
    op.drop_column('ty_idc', 'created_at')
    op.drop_column('ty_idc', 'created_by')
    op.add_column('ty_country', sa.Column('updated_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='更新时间'))
    op.add_column('ty_country', sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建时间'))
    op.drop_column('ty_country', 'updated_at')
    op.drop_column('ty_country', 'updated_by')
    op.drop_column('ty_country', 'created_at')
    op.drop_column('ty_country', 'created_by')
    op.add_column('ty_continent', sa.Column('updated_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='更新时间'))
    op.add_column('ty_continent', sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建时间'))
    op.drop_column('ty_continent', 'updated_at')
    op.drop_column('ty_continent', 'updated_by')
    op.drop_column('ty_continent', 'created_at')
    op.drop_column('ty_continent', 'created_by')
    op.add_column('ty_city', sa.Column('updated_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='更新时间'))
    op.add_column('ty_city', sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='创建时间'))
    op.drop_column('ty_city', 'updated_at')
    op.drop_column('ty_city', 'updated_by')
    op.drop_column('ty_city', 'created_at')
    op.drop_column('ty_city', 'created_by')
    # ### end Alembic commands ###
