"""init commit

Revision ID: d6ea28af0171
Revises: 39cc85072ef9
Create Date: 2022-01-14 14:23:09.345848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ea28af0171'
down_revision = '39cc85072ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ty_idc_ibfk_1', 'ty_idc', type_='foreignkey')
    op.add_column('ty_vendor', sa.Column('remarks', sa.String(length=256), nullable=True, comment='备注'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ty_vendor', 'remarks')
    op.create_foreign_key('ty_idc_ibfk_1', 'ty_idc', 'ty_vendor', ['vendor_id'], ['id'])
    # ### end Alembic commands ###
